### ISSUE TITLE
Cannot run portable POH 1.9.0

### ISSUE THREAD

**Issue by dantrolene** [informatici/openhospital#108]
While running the oh.bat I am stuck at the cmd prompt interface and oh doesnt start. Attaching below the file.
Please guide what am I missing?
Thanks.
[New Text Document.txt](https://github.com/informatici/openhospital/files/4618044/New.Text.Document.txt)

**Comment by mwithi** [comment]
Hi @dantrolene, it seems it is waiting the connection with the database, are you on Windows? It probably it asks you to allow mysql server to run locally and open the port on the local firewall.

Why are you running release 1.9.0?

**Comment by dantrolene** [comment]
Hi @mwithi 
I am running the portable version 1.9.0. (poh-win32-0.0.5-1.9.0.zip) I downloaded from website. What I understand from reading the manual was the portable version has self contained mysql and does not need any separate installation of mysql. Am I wrong? As far as I understand my firewall is not blocking any ports.

**Comment by mwithi** [comment]
Hi @dantrolene 
no, you are not wrong, I mean that the bundled mysql server needs to run and to listen on the first free port locally (starting from 3306) hence to be allowed by the firewall.

Are you sure it didn't ask and you answered "no" the first time? To try again and trick the windows firewall you can just change the folder name.

Do you have any other antivirus/firewall installed? What version of Windows? Also, I was asking the why you downloaded 1.9.0 and not 1.9.1?

**Comment by dantrolene** [comment]
Hey @mwithi 
Thanks for suggesting. I somehow missed the 1.9.1 release. That may have been a bug with 1.9.0 as the latest release is working fine.  
There was no prompt for permission on starting 1.9.0 though, and I checked firewall too and tried renaming the folder. I am noob at codes to understand what was wrong with it. 

I am looking forward to trying to manage OPD data for out small clinic with OH. Lets hope everything goes right. I will be back if I need any help.
Thank you so much.

**Comment by mwithi** [comment]
You're welcome @dantrolene, don't you mind to fullfill this online form in order to better support you in case in future?
https://docs.google.com/forms/d/e/1FAIpQLSeMeTnETkHiGLRqK83nNsIBYQk86XgaZWE2yDfn1f0crj6x2A/viewform

Thanks!
