### ISSUE TITLE
Update OpenHub Settings

### ISSUE THREAD

**Issue by emecas** [informatici/openhospital#113]
Source code locations and project links are pointing to SourceForge.net

https://www.openhub.net/p/open_hospital

https://www.openhub.net/p/open_hospital/settings

**Comment by mwithi** [comment]
Done, added other missing info. Don't know what will happen about previous code statistics...

**Comment by emecas** [comment]
>> About Code Locations

>> Open Hub's statistics are derived from analysis of the project's source code history as maintained by the project's repository. Accordingly, it is crucial that this information be maintained accurately.

>> Open Hub can combine data from multiple code locations to create a composite and complete set of statistics for a project. This means that a project:




>> can include both a read-only historical repository and a newer, active repository that accurately reflect the entire history of a project even if its code has been moved or its SCM has been changed.




https://www.openhub.net/p/open_hospital/enlistments
