### ISSUE TITLE
Include changelog between versions in doc/ folder

### ISSUE THREAD

**Issue by mwithi** [informatici/openhospital#12]
The idea is to equip the package with a descriptive changelog, to be copied also in the description of the release when it is passed from Draft to Public.

However, a unique changelog of multiple components is not possible, just as it is necessary to think of a human readable changelog.

**Comment by mwithi** [comment]
In the end I opted to equip each component of its changelog, to be updated by hand before each release (tag).

Then the manuals (generated by the new process) and the last changelog of each component (or all?) Will be copied into the package.

Any suggestions for improvement?

**Comment by pviotti** [comment]
Assuming that the changelog is read by a (more or less technically expert) user, I'm in favor of keeping only one changelog, for simplicity. Maybe we could keep it in this repo, and take care of updating it as soon as relevant fixes or new features get merged to the master branch of (g)ui or core.  

Regarding the format, I've used and seen used this one: https://keepachangelog.com/en/1.0.0/
It's a simple markdown format that lists added, changed and fixed things.

**Comment by pviotti** [comment]
On a second thought, to minimize the effort (since this project is run by volunteers) and since rarely anybody reads changelogs anyway, I'm ok with the proposal by @mwithi as a starting point. This however would require a certain discipline in keeping the git commit logs meaningful and readable.

**Comment by mwithi** [comment]
We are always promoting [smart-commits](https://openhospital.atlassian.net/wiki/spaces/OH/pages/14909466/Smart+Commits).

However, we should 'squash&merge' manually the changelogs in a user-friendly format as comment of each release
