### ISSUE TITLE
Replace deprecated tool netstat in oh.sh 

### ISSUE THREAD

**Issue by pviotti** [informatici/openhospital#131]
`netstat` has been deprecated some years ago in favor of other tools more commonly available in Linux distributions, so it should be replaced in `oh.sh`
https://dougvitale.wordpress.com/2011/12/21/deprecated-linux-networking-commands-and-their-replacements/

**Comment by yabets** [comment]
Hello @pviotti, 
I would like to take this up if no one is currently working on it.

**Comment by pviotti** [comment]
Sounds good thanks!

**Comment by yabets** [comment]
The blog post by Doug Vitale suggests that `ss` as a replacement for `netstate`. 

Following is my proposed code change
`netstat -tna | grep -e '^tcp' | awk '{ print $4 }' | grep ":$mysql_port"` to
`ss -tna | awk '{ print $4 }' | grep ":$mysql_port"`

ss -t will filter tcp results. `ss` result doesn't have `Proto` column hence I am removing `grep -e '^tcp'`

Following are outputs of the two commands
![netstat -tna](https://user-images.githubusercontent.com/16535711/95584858-fbef5580-0a5b-11eb-857e-a377abd0b337.png)
![ss -tna](https://user-images.githubusercontent.com/16535711/95584867-ff82dc80-0a5b-11eb-8caa-8cdfbb874f05.png)

**Comment by pviotti** [comment]
looks good. Try testing it (even just manually) and then submit a PR. Thanks again!
