### ISSUE TITLE
Rewrite oh.bat as a PowerShell script

### ISSUE THREAD

**Issue by pviotti** [informatici/openhospital#132]
PowerShell has been included in Windows operating system since Windows XP SP2, so we should replace [oh.bat](https://github.com/informatici/openhospital/blob/master/poh-bundle-win/oh.bat) with a PowerShell script. This would make it simpler, more robust and easier to test - and it would solve issues like the one reported in [OP-179](https://openhospital.atlassian.net/browse/OP-179).

**Comment by mwithi** [comment]
Moved to Jira OP-338
