### ISSUE TITLE
Move 'bundles' and 'rpt' to core component

### ISSUE THREAD

**Issue by mwithi** [informatici/openhospital#14]
- [ ] Move 'bundles' and 'rpt' folders from 'core' component because they are only needed at runtime (in classpath)
- [x] Remove 'myqsl' from 'gui' one because they are only needed for the DB creation

This can wait PRs https://github.com/informatici/openhospital-core/pull/47 (in progress)
and https://github.com/informatici/openhospital-gui/pull/25 (in progress)

**Comment by pviotti** [comment]
is this issue still open? (I can't find some of the folders mentioned above)

**Comment by mwithi** [comment]
Yes, 'mysql' folder has already been moved. Need time to move the other ones because they are linked to Transifex.

**Comment by mwithi** [comment]
closing in favor of OP-291
