### ISSUE TITLE
Release changelog

### ISSUE THREAD

**Issue by mwithi** [informatici/openhospital#148]
Replace the current release changelog
![image](https://user-images.githubusercontent.com/2938553/100156415-23ce3780-2ea9-11eb-9ef0-44dfc78add98.png)

with the Atlassian one (e.g. v1.11.0)
![image](https://user-images.githubusercontent.com/2938553/100163096-3a7a8b80-2eb5-11eb-8de5-12b5230adc62.png)
See https://openhospital.atlassian.net/secure/ReleaseNote.jspa?projectId=10202&version=10005

Not sure it can be achived with:
- https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/
- https://developer.atlassian.com/cloud/jira/software/rest/intro/

[source](https://developer.atlassian.com/cloud/jira/platform/#rest-apis)

**Comment by pviotti** [comment]
good idea. Maybe a specific GitHub Action for Atlassian can be useful. For instance this one https://github.com/marketplace/actions/jira-changelog

**Comment by mwithi** [comment]
Closing this issue, moved to OP-467.

Thanks!
