### ISSUE TITLE
Pharmacy - duplicates into Pharmaceuticals

### ISSUE THREAD

**Issue by virivigio** [informatici/openhospital#19]
Windows 7 32bit 
Portable OH pre-release 1.9.0
No changes applied to default database.

The Pharmaceuticals page displays 4 times each pharma when "select type ALL" but just one when I select the proper subset(eg DRUGS. See Pictures 1 and 2)
![Pict1](https://user-images.githubusercontent.com/1875906/62417476-e957e000-b650-11e9-9e64-f3ffc48403f0.png)
![Pict2](https://user-images.githubusercontent.com/1875906/62417477-e9f07680-b650-11e9-82a9-8dd8c2978e48.png)

If this is not an error but has a reason, at least it's confusing for the user.

**Comment by virivigio** [comment]
Updating a single element in "ALL" page results in 4 lines being updated

![Pict3](https://user-images.githubusercontent.com/1875906/62417483-1efcc900-b651-11e9-9430-5876b96478a6.png)

(the highlighted line in the picture is the one selected for update)
on database I see just one line in table medicaldsr
![Pict4](https://user-images.githubusercontent.com/1875906/62417569-f8d82880-b652-11e9-8629-ffba9f4d0ecc.png)

**Comment by virivigio** [comment]
Also Stock visualizes 4 lines per pharmaceutical
![stock](https://user-images.githubusercontent.com/1875906/62445650-0976c480-b761-11e9-8f23-5e27a48dbf77.png)

**Comment by mwithi** [comment]
Thanks for reporting this @virivigio , we will look at it ASAP

**Comment by mwithi** [comment]
Fixed with core 384239b8dee74a38400804fdff931dfbb8be2bc4
