### ISSUE TITLE
Problems when printing Exam results in Jasper Reports

### ISSUE THREAD

**Issue by virivigio** [informatici/openhospital#23]
Laboratory Browsing (v1.1)
Select PRINT TABLE
Keep default "Open with Jasper Reports"

the attached report does not report any patient reference (name or id)

![Schermata 2019-08-07 alle 12 19 30](https://user-images.githubusercontent.com/1875906/62615613-e6d5de80-b90d-11e9-9334-de81b8fa5455.png)

is that correct?

**Comment by mwithi** [comment]
Yes, it's correct, anyway that report shoudl be seriously improved
