### ISSUE TITLE
Filtering for Male/Female does not work in Vaccines

### ISSUE THREAD

**Issue by virivigio** [informatici/openhospital#26]
As per image: selecting Male or Female and hitting search does not filter rows

![Schermata 2019-08-09 alle 10 19 24](https://user-images.githubusercontent.com/1875906/62764969-6a6b0900-ba8f-11e9-9e92-31a4d5fdb058.png)

**Comment by mwithi** [comment]
Fixed with gui 182bbc8c2fbcdbda1164bb342cd30b34e1d4206c
