### ISSUE TITLE
Date Filtering problems in Vaccines

### ISSUE THREAD

**Issue by virivigio** [informatici/openhospital#27]
Have a look at first image: the day of the vaccine is equal to the end-search-date in form.

![1](https://user-images.githubusercontent.com/1875906/62765594-b8ccd780-ba90-11e9-8318-8827f229adcb.png)

If I move the search filter to the following day the record disappears

![2](https://user-images.githubusercontent.com/1875906/62765627-ca15e400-ba90-11e9-82ab-148807c3eed2.png)

**Comment by mwithi** [comment]
Fixed with core c958993660d959eeaed2ca2f0e139988eb782fc6
