### ISSUE TITLE
Cannot make OH work with OpenFire

### ISSUE THREAD

**Issue by virivigio** [informatici/openhospital#28]
I followed https://github.com/informatici/openhospital-doc/blob/master/doc_admin/AdminManual.adoc#5-9-xmpp-properties
and downloaded openfire 4.4.0

Set XMPPMODULEENABLED and SINGLEUSER
Created and Admin2 in OH

Every time I start OH I get:
![VirtualBox_IE10 - Win7_11_08_2019_17_36_04](https://user-images.githubusercontent.com/1875906/62835980-98527800-bc5e-11e9-9c2d-28f72ecbf9f6.png)

even if I drop Admin2 user from OpenFire...

I'm not sure this is an issue on OH but at least it is not working out of the box

**Comment by mwithi** [comment]
Hi @virivigio, it is saying that the password is not matching, maybe you created the admin2 user in OpenHospital AND in OpenFire? Only in OH is needed and the one in OpenFire will be created automatically at the first login. 

So, as suggested, drop the admin2 in OpenFire and just login again with it from OpenHospital.

Let us know, thanks!

**Comment by virivigio** [comment]
I have the very same error in all of the following cases:
"admin2" exists in OH but not in OF: I see the user gets created in OF but the error is raised
"admin2" exists both in OH and OF: I have the error even if I set the same password in both environments

**Comment by virivigio** [comment]
Do you need / prefer to do some remote monitoring / activity on my system?

**Comment by mwithi** [comment]
> "admin2" exists both in OH and OF: I have the error even if I set the same password in both environments

You HAVE NOT to create the user (and therefore set any password) in both system, because they are stored in a different way: is OH that creates the user in OF (with the correct password) if it is missing.

> "admin2" exists in OH but not in OF: I see the user gets created in OF but the error is raised

This is not expected (I've tried myself now, OF v4.0.1): it should just create the user in OF and that's all. Can you please delete the user from OF (only) and login again in OH?

Thanks

**Comment by virivigio** [comment]
I haven't created the user manually.

Anyway: new test. OF contains only "Virgilio" administrative user.
I launch OH, login with "admin2" and "password" and it reports the error above.
In OF -now- I see the admin2 user but i CANNOT LOGIN INTO of with "admin2/password"

Anyway I understand you cannot reproduce so I suggest we wait for another independent test. Maybe this issue is related to something on my environment I do not identify...

**Comment by mwithi** [comment]
> I launch OH, login with "admin2" and "password" and it reports the error above.

This is strange, I don't know if maybe the OF database is dirty

> In OF -now- I see the admin2 user but i CANNOT LOGIN in OF with "admin2/password"

This is correct, OH created the admin2 user in OF, anyway that user is not meant to be used from OF itself but only from Communication module, within OH. If you open two different istances of OH and login with different users, are you able to see each user logged in the Communication module and make them chatting?

In other words: OF only act as a server for the messages exchange (XMPP protocol) and, once properly set, it should not require others actions.

**Comment by virivigio** [comment]
OH opens without communication module enabled...
I'll try with a clean OF installation

Il lun 19 ago 2019, 22:02 Alessandro Domanico <notifications@github.com> ha
scritto:

**Comment by mwithi** [comment]
Please again using the latest `develop` branches and in case open a new [Jira issue](https://openhospital.atlassian.net/jira/software/c/projects/OP/issues/?filter=allopenissues). (we close GitHub issues)

Thanks!
