### ISSUE TITLE
I18N: delete patient confirmation dialog seems hard coded in italian

### ISSUE THREAD

**Issue by virivigio** [informatici/openhospital#53]
Please check attached picture. Other dialog windows examined so far use  OK/Cancel labels
Documentation https://github.com/informatici/openhospital-doc/blob/master/doc_user/UserManual.adoc#1032-delete-a-patient-delete-patient suffers same issue

![Schermata 2020-02-11 alle 10 07 02](https://user-images.githubusercontent.com/1875906/74223227-8bb6e700-4cb6-11ea-9bf7-6eae4e2deec6.png)

**Comment by mwithi** [comment]
Solved by set the locale as per generalData.properties as defaultLocale of JOptionPane components, as suggested here: https://stackoverflow.com/a/18189543/5309541

The change will be available by the next release

**Comment by mwithi** [comment]
Fixed with https://github.com/informatici/openhospital-core/commit/3b37d1d20d66f6f5f6758cdef59514fa03623f6c
