### ISSUE TITLE
Improvement: reports lack measurement units

### ISSUE THREAD

**Issue by virivigio** [informatici/openhospital#56]
As in picture, height and weight do not state if it is cm, ft, lb, kg, ...
This is common to all reports providing patient information

![Schermata 2020-02-11 alle 12 03 46](https://user-images.githubusercontent.com/1875906/74231525-13a4ed00-4cc7-11ea-9114-d3bc16851a2a.png)

**Comment by thodorisbais** [comment]
Unfortunately, I'm a bit time poor at the moment, so I couldn't get the chance to have a thorough look into the code.

However, if dealing with Units of Measurement becomes an issue at any moment, why not use the [Units of Measurement API](https://github.com/unitsofmeasurement) (JSR-385)?

[JSR-385](https://jcp.org/en/jsr/detail?id=385) is a stable Java library that helps you perform any kind of UoM-related operation without having to worry about the content or business details.

Have a look at the [api](https://github.com/unitsofmeasurement/unit-api) itself or the RI (Reference Implementation) of this JSR.

And in case that's not clear yet, I'm pretty sure the following line will demystify quite some concerns:

```java 
final Quantity<Mass> mass = Quantities.getQuantity(75, Units.KILOGRAM);
		System.out.println(mass);
```

That is, the above will print "75 kg"

In addition, you can [here](https://github.com/thodorisbais/jsr385-examples) find a repo that showcases the easiness of using this library

I'd be happy to hear your views as well.

Thodorris

**Comment by estromsnes** [comment]
I would assume that it's sufficient to add unit to the report label as height and weight as far as I can see are meant to be centimeters and kilograms (based on the database columns).
I can easily fix the the Jasper template, but I'm having trouble when I try to use the newly compiled reports in the downloadable app. I get various nullpointer and other Jasper exceptions. I will try some more in the near future...

**Comment by mwithi** [comment]
@estromsnes yes, it would be sufficient, could you try tu use iReport 3.0.0 (Classic) to compile the reports?

**Comment by mwithi** [comment]
@thodorisbais concerning this very issue, it will be sufficient what @estromsnes suggested.
Nevertheless it would be nice to provide the Application a small measurement management (with the main ones used among different countries). We can open a Jira issue for that, what do you think?

**Comment by estromsnes** [comment]
I managed to modify and compile the report using iReport 3.0.0.  A new pull request has been made :-) 

Is Jasper still the preferred framework for reporting in the new version of OpenHospital? If so, I might help in other reporting issues, like adding support for translations, etc.

**Comment by mwithi** [comment]
Yes @estromsnes, it is! And you are welcome to do that!
Please have a look here: https://openhospital.atlassian.net/issues/?jql=labels%20%3D%20%22reporting%22

I don't know if we are eager for OP-104 (we are still tight to Java6 at this stage) but sure other improvements are waiting to be done (e.g. OP-105 and OP-95) 

Thanks!!!

**Comment by mwithi** [comment]
Closed with https://github.com/informatici/openhospital-gui/pull/64
