### ISSUE TITLE
Empty Expiring Report for Pharmaceuticals

### ISSUE THREAD

**Issue by virivigio** [informatici/openhospital#59]
I added a lot of Pharmaceutical as per picture, expiring in one day
![Schermata 2020-02-11 alle 15 32 57](https://user-images.githubusercontent.com/1875906/74245962-1bbf5580-4ce4-11ea-9cf5-378d94b1d3d7.png)

isn't it supposed to show in the Expiring Report? (maybe I have a wrong understanding of the workflow)

![Schermata 2020-02-11 alle 15 33 58](https://user-images.githubusercontent.com/1875906/74245905-0a764900-4ce4-11ea-97d0-a5e796b99ffc.png)

but the report is empty "il documento non contiene nessuna pagina" (in italian).

**Comment by mwithi** [comment]
Fixed with:
https://github.com/informatici/openhospital-gui/commit/b2ed3d2086d29f05ad49b9e3824c05f1d7065a8c
https://github.com/informatici/openhospital-core/commit/8c835f836e8be6b7d104bc9470c96aa5a72dc57c
