### ISSUE TITLE
Include translations from Transifex into portable distribution

### ISSUE THREAD

**Issue by pviotti** [informatici/openhospital#6]
More details, with WorkFlow @ [Jira OP-103](https://openhospital.atlassian.net/projects/OP/issues/OP-103)

**Comment by mwithi** [comment]
For this issue maybe we will move 'bundle' and 'rpt' folder to 'core' component, so can be used also by next 'ui' component

**Comment by mwithi** [comment]
At the moment the workflow is "closed", because Transifex-GitHub integration allows to pull-request on the 'gui' component any language bundle whenever is 100% translated.

However, it would be nice if pull-request could be triggered on demand (Transifex Team is working on it)

**Comment by mwithi** [comment]
I’m putting this issue because many things have chagned and also Transifex github-integration has been improved a lot so far.
