### ISSUE TITLE
New Patien Exam Error on moultiple results (proc 2)

### ISSUE THREAD

**Issue by virivigio** [informatici/openhospital#60]
While trying to replicate https://github.com/informatici/openhospital-doc/blob/master/doc_user/UserManual.adoc#733-laboratory-multiple-insert I tried to insert the following exam

![Schermata 2020-02-11 alle 18 07 35](https://user-images.githubusercontent.com/1875906/74260299-90e95580-4cf9-11ea-81cc-507d6d4680e2.png)

log shows:
`[11/feb/2020 18:07:20] [admin:admin] WARN - SQL Error: 1048, SQLState: 23000
[11/feb/2020 18:07:20] [admin:admin] ERROR - Column 'LABR_DESC' cannot be null`

**Comment by mwithi** [comment]
Fixed with:
https://github.com/informatici/openhospital-core/commit/84fc34ccd53f87de7be2c7b07d1982ce6c1fd5cf
https://github.com/informatici/openhospital-gui/commit/d77e9648aa3b353d4f2aa7920bcfd7e9660ea365
