### ISSUE TITLE
Report HMIS 108 not reporting all patients

### ISSUE THREAD

**Issue by virivigio** [informatici/openhospital#63]
I created a test patient as follows:
![Schermata 2020-02-13 alle 11 52 41](https://user-images.githubusercontent.com/1875906/74427480-7b8a3d80-4e57-11ea-87dc-b05a79506116.png)

but report 108 does not report any AIDS admissions

![Schermata 2020-02-13 alle 11 51 51](https://user-images.githubusercontent.com/1875906/74427474-788f4d00-4e57-11ea-9031-c7669672d33e.png)

**Comment by mwithi** [comment]
Hi @virivigio, could you please verify if the admission appears once the patient has been discharged?
The report should count only closed admissions in the choosen period.

**Comment by virivigio** [comment]
Yes
I discharger the test patient with
![Schermata 2020-02-16 alle 08 55 05](https://user-images.githubusercontent.com/1875906/74601100-428ddb00-509a-11ea-8fff-c82596b9c50d.png)

and the report (InPatient) now is
![Schermata 2020-02-16 alle 08 56 00](https://user-images.githubusercontent.com/1875906/74601102-49b4e900-509a-11ea-8976-343807ea3cb2.png)

**Comment by mwithi** [comment]
Ok, so I think a good solution would be to announce this behavior in the report itself like "* showing only closed admissions"

**Comment by mwithi** [comment]
Solved with https://github.com/informatici/openhospital-gui/commit/67375c0c51dea278e192be609aabb74b438a7769
