### ISSUE TITLE
Build error on Mac OSX

### ISSUE THREAD

**Issue by thodorisbais** [informatici/openhospital#71]
Hello,

I'm getting the following error while building from `build_poh.sh` :

<pre>sed: 1: "CHANGELOG.md": invalid command code C</pre>

_System_
**Mac OS Catalina 10.15.1 (19B88)**

Does the project work on OSX or am I missing something?

Thodoris

**Comment by emmeblm** [comment]
Hey Thodoris,

I ran into the same issue.. I'm planning on putting a PR for the fix, but basically you can make your environment work by replacing both sed and head lines (commented here) in the script by:

```
# sed -i "s/VERSION/$version/g" CHANGELOG.md

sedi=(-i)
headn=(--lines=-4)
case "$(uname)" in
  Darwin*)
    sedi=(-i "")
    headn=(-n 4)
esac

sed "${sedi[@]}" -e "s/VERSION/$version/g" CHANGELOG.md

# head --lines=-4 CHANGELOG.md > CHANGELOG
head "${headn[@]}" CHANGELOG.md > CHANGELOG
```

That will fix the issue and make the script compatible with MacOs..

**Comment by mwithi** [comment]
Thanks @emmeblm for the hint! The truth is that the script is meant for Travis CI build (so Linux) for the releases packaging, it is not meant for developers for whom is suggested to clone each repository separately. Indeed, this repository, is not yet linked to "api" and "ui" repository, which will be included in future releases and so, also the actual script will change.

Said so, if the fix works for both Linux and MacOS we can just adopt it, and Travis will test it in the PR itself ;)

**Comment by emmeblm** [comment]
That sounds great @mwithi ! I'll create a PR with this minor change then.. 
Since you mention this is not meant for developers, I'm thinking also that it would be really nice to have a more detailed README or CONTRIBUTE file with some basic rules and development guidelines for contributors.. Is there anything like that already? I couldn't find it..

**Comment by mwithi** [comment]
Yes @emmeblm we have the README.md and the Wiki linked in each modules, although we can still improved them.

**Comment by pviotti** [comment]
The build script has been rewritten as a Makefile, and anyway it was not meant to be run by end users - we improved the documentation too (#141), so hopefully this will be more clear.  
As per the original question: AFAIK OH is not tested on Mac OS, though it should run on every platform supported by Java. Hope this helps.
